title:              Self-Teaching Blog
email:              lgtwvs@gmail.com
description:        Study hard! plz..
author:             Seho
baseurl:            ""
url:                "https://leeseho.github.io"

# Social Profiles
#twitter_username:   SBootstrap
github_username:    leeseho
#facebook_username:  StartBootstrap
#linkedin_username:

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site


google_fonts: "Nanum+Gothic:400,700"

google_analytics : UA-155125347-1
