# Site settings
title: Untitled
description: > # this means to ignore newlines until "baseurl:"
  IT, Development Blog
baseurl: "https://leeseho.github.io" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site you most probably don't need to set it

# Build settings
markdown: kramdown
paginate: 5 # pagination based on number of posts
paginate_path: "page/:num"
highlighter: pygments
gems: [jekyll-paginate, jekyll-coffeescript]

# comments
disqus: # add disqus shortna
#me here

# author info
# add your appropriate info here
author: Lee Seho # your name
bio:    # your bio
email: lgtwvs@gmail.com
email_md5: # md5 hash of your email
twitter_username:
github_username: leeseho

# Theming options
# These settings are mandatory.
theme:              'blue-pink'

# drawer theming
drawer:
  text_color:       'grey-600'
  header_color:     'blue-500'
  navigation_color: 'grey-200'
# footer theming
footer:
  text_color: 'blue-grey-200'
  color: 'blue-grey-600'
